apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <NAME_SERVICE>-credentials
  namespace: redis-test
data:
  host: cmZzLWNhcnQtbWFpbi1jYWNoZS50ZXN0LnN2Yw==
  password: cmVkaXMtZmFpbG92ZXI=
  port: MjYzNzk=
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: <NAME_SERVICE>
  namespace: redis-test
spec:
  auth:
    secretPath: beta-test-cache-del-me-credentials
  redis:
    customConfig:
    - maxmemory 500M
    - maxmemory-policy volatile-lru
    image: registry.eapteka.ru/cache-dockerhub/redis:7.4-alpine3.21
    imagePullPolicy: IfNotPresent
    replicas: 3
    port: 6379
    resources:
      limits:
        cpu: 400m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
  sentinel:
    customConfig:
    - down-after-milliseconds 5000
    - failover-timeout 3000
    image: registry.eapteka.ru/cache-dockerhub/redis:7.4-alpine3.21
    imagePullPolicy: IfNotPresent
    replicas: 3
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
